### PR TITLE
Added Selection Sort using Recursion

### PR DESCRIPTION
**Pull request by sayyed-nabeel**

### CODE REVIEW

**Comment by BrentZ-1849203** [comment]
Hey there, your depth first search does not seem to work if I run it.

**Comment by BrentZ-1849203** [comment]
Hey there, could you remove the search algorithms from your commit please.

**Comment by sayyed-nabeel** [comment]
Can you tell me how to do this bcoz whenever I'm trying to contribute new pull request without the search algos it reopens all of my previous closed pull requests (which contains the file I don't intend to merge).

**Comment by BrentZ-1849203** [comment]
Have you tried making a new fork? I haven't had that issue before so I can't say for sure how to solve it from the top if my head. If the new fork does not work you can maybe try to go back to a previous commit on your old fork (being the one without the unwanted comitted files) and try to push that one again. Maybe then you can add the wanted file back and try again. :)

**Comment by sayyed-nabeel** [comment]
Try it now I have deleted all the unnecessary commits.

**Comment by BrentZ-1849203** [comment]
Great, thanks for the pull request 💯

**Comment by sayyed-nabeel** [comment]
Thanks a for accepting the pull request.😊

**Pull request merged**
